version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test-client:
    working_directory: /home/circleci/project/client
    executor: node/default
    steps:
      - checkout
      - run:
          command: echo "test-client"
          name: Client Testing Initiation
      - node/install-packages:
          pkg-manager: npm
          app-dir: /home/circleci/project/client
      - run: 
          command: npm test
          name: Testing

  test-server:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: echo "test-server"
      - run: cd server
      - run: npm test
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test-client
  

