version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test-client:
    working_directory: ~/client
    executor: node/default
    steps:
      - checkout
      - run:
          command: echo "test-client"
          name: Client Testing Initiation
      - node/install-packages:
          pkg-manager: npm
          app-dir: ~/client
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          command: ls
          name: list-directories
      - run:
          command: cd client && npm run test
          name: Testing

  test-server:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: echo "test-server"
      - run: cd server
      - run: npm run test
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test-client
  

